/**
 * Mojin — i18n strings (EN / DE)
 */
const MOJIN_I18N = {
  en: {
    nav_features: "Features",
    nav_templates: "Templates",
    nav_pricing: "Pricing",
    nav_docs: "Docs",
    nav_cta: "Start Free",

    hero_badge: "Remotion + Particle Physics",
    hero_title_1: "Make Your",
    hero_title_2: "Videos Move",
    hero_sub: "Fine-tune spring physics, particle effects, and motion curves — export studio-quality video from your browser.",
    hero_cta_primary: "Start Editing Free",
    hero_cta_secondary: "Watch Demo",
    hero_scroll: "Scroll",

    how_eyebrow: "How It Works",
    how_title: "Three steps to a better video",
    how_sub: "Upload a template, adjust the parameters, export. No After Effects required.",
    step1_title: "Choose a Template",
    step1_desc: "Pick from 50+ professional Remotion compositions — cinematic intros, text reveals, logo animations, particle effects.",
    step2_title: "Fine-Tune Motion",
    step2_desc: "Adjust spring stiffness, damping, particle count, force fields, easing curves — every slider updates the preview instantly.",
    step3_title: "Export HD",
    step3_desc: "Click export and get a 1080p MP4 in seconds. Or go 4K. Or GIF. Your call — our servers handle the render.",

    feat_eyebrow: "Features",
    feat_title: "Motion intelligence,\nbaked in",
    feat_sub: "Not just sliders — a real physics engine and GPU particle system driving every frame.",
    feat1_title: "Spring Physics",
    feat1_desc: "Control stiffness, damping, and mass for every animated element. Physics-based motion that actually feels real.",
    feat2_title: "Particle Engine",
    feat2_desc: "GPU-accelerated particles: 5,000+ at 60fps. Boids, fluid, constellation, firework — 12 behavior presets.",
    feat3_title: "Live Preview",
    feat3_desc: "Remotion Player embedded right in the editor. Every slider change previews instantly — no render wait.",
    feat4_title: "Export HD",
    feat4_desc: "Server-side render with Remotion Lambda. MP4, WebM, GIF, APNG. 720p to 4K. Done in seconds.",
    feat5_title: "Template Library",
    feat5_desc: "50+ professional compositions. Cinematic, text, logo, particles, transitions. Download as-is or customize.",
    feat6_title: "AI Motion Assist",
    feat6_desc: "AI analyzes your content and suggests motion presets that match the energy and pacing of your brand.",

    demo_eyebrow: "Live Demo",
    demo_title: "Try it right now",
    demo_sub: "Adjust the sliders — watch the preview update in real time. No signup needed.",
    demo_param_spring: "Spring Stiffness",
    demo_param_particles: "Particle Count",
    demo_param_speed: "Animation Speed",
    demo_param_hue: "Color Hue",
    demo_open: "Open Full Editor",

    tpl_eyebrow: "Templates",
    tpl_title: "Start with a template",
    tpl_sub: "Every template is a fully editable Remotion composition. Use it as-is or make it yours.",
    tpl1_name: "Cinematic Intro",
    tpl1_desc: "Dramatic title reveal with particle trails and depth-of-field blur.",
    tpl2_name: "Text Reveal",
    tpl2_desc: "Spring-animated characters with custom easing and stagger delay.",
    tpl3_name: "Logo Burst",
    tpl3_desc: "Logo entrance with radial particle explosion and glow.",
    tpl4_name: "Particle Storm",
    tpl4_desc: "Full-frame GPU particle simulation with gravity wells and color gradients.",
    tpl5_name: "Fluid Wipe",
    tpl5_desc: "Scene transition using fluid simulation — organic, smooth, physical.",
    tpl6_name: "Neon Pulse",
    tpl6_desc: "Rhythmic neon glow animation with particle sync to audio waveform.",
    tpl_use: "Use Template",
    tpl_preview: "Preview",

    price_eyebrow: "Pricing",
    price_title: "Simple, honest pricing",
    price_sub: "Start free. Upgrade when you need more exports, resolution, or API access.",
    price_free: "Free",
    price_free_sub: "Forever",
    price_pro: "Pro",
    price_pro_per: "/ month",
    price_studio: "Studio",
    price_studio_per: "/ month",
    price_cta_free: "Get Started Free",
    price_cta_pro: "Start Pro Trial",
    price_cta_studio: "Contact Sales",
    price_most_popular: "Most Popular",

    footer_tagline: "Motion intelligence for every creator. Powered by Remotion and GPU particle physics.",
    footer_col_product: "Product",
    footer_col_templates: "Templates",
    footer_col_developers: "Developers",
    footer_col_company: "Company",
    footer_copyright: "© 2026 Mojin. All rights reserved.",
    footer_made_by: "A Lunexo Labs product.",
  },
  de: {
    nav_features: "Features",
    nav_templates: "Vorlagen",
    nav_pricing: "Preise",
    nav_docs: "Docs",
    nav_cta: "Kostenlos starten",

    hero_badge: "Remotion + Partikelphysik",
    hero_title_1: "Deine Videos",
    hero_title_2: "in Bewegung",
    hero_sub: "Federkräfte, Partikeleffekte und Bewegungskurven fein abstimmen — und professionelle Videos direkt im Browser exportieren.",
    hero_cta_primary: "Kostenlos starten",
    hero_cta_secondary: "Demo ansehen",
    hero_scroll: "Scrollen",

    how_eyebrow: "So funktioniert's",
    how_title: "Drei Schritte zum besseren Video",
    how_sub: "Vorlage auswählen, Parameter anpassen, exportieren. Kein After Effects nötig.",
    step1_title: "Vorlage auswählen",
    step1_desc: "50+ professionelle Remotion-Kompositionen — cineastische Intros, Textanimationen, Logo-Explosionen, Partikeleffekte.",
    step2_title: "Bewegung verfeinern",
    step2_desc: "Federsteifigkeit, Dämpfung, Partikelanzahl, Kraftfelder, Easing-Kurven anpassen — jeder Regler aktualisiert die Vorschau sofort.",
    step3_title: "In HD exportieren",
    step3_desc: "Export-Button klicken und in Sekunden ein 1080p MP4 erhalten. Oder 4K. Oder GIF. Unsere Server übernehmen das Rendering.",

    feat_eyebrow: "Features",
    feat_title: "Motion-Intelligenz,\neingebaut",
    feat_sub: "Nicht nur Regler — eine echte Physik-Engine und GPU-Partikelsystem für jeden Frame.",
    feat1_title: "Federphysik",
    feat1_desc: "Steifigkeit, Dämpfung und Masse für jedes animierte Element steuern. Physikbasierte Bewegung, die sich echt anfühlt.",
    feat2_title: "Partikel-Engine",
    feat2_desc: "GPU-beschleunigte Partikel: 5.000+ bei 60fps. Schwarm, Fluid, Konstellation, Feuerwerk — 12 Verhaltens-Presets.",
    feat3_title: "Live-Vorschau",
    feat3_desc: "Remotion Player direkt im Editor. Jede Reglerchange gibt sofort Vorschau — kein Warten auf Render.",
    feat4_title: "HD-Export",
    feat4_desc: "Server-seitiges Rendering mit Remotion Lambda. MP4, WebM, GIF, APNG. 720p bis 4K. In Sekunden fertig.",
    feat5_title: "Vorlagenbibliothek",
    feat5_desc: "50+ professionelle Kompositionen. Cineastisch, Text, Logo, Partikel, Übergänge. As-is oder anpassen.",
    feat6_title: "KI-Bewegungsassistent",
    feat6_desc: "KI analysiert deinen Content und schlägt Bewegungs-Presets vor, die Energie und Tempo deiner Marke treffen.",

    demo_eyebrow: "Live Demo",
    demo_title: "Jetzt direkt ausprobieren",
    demo_sub: "Regler anpassen — Vorschau aktualisiert sich in Echtzeit. Kein Account nötig.",
    demo_param_spring: "Federsteifigkeit",
    demo_param_particles: "Partikelanzahl",
    demo_param_speed: "Animationsgeschwindigkeit",
    demo_param_hue: "Farbton",
    demo_open: "Vollständigen Editor öffnen",

    tpl_eyebrow: "Vorlagen",
    tpl_title: "Mit einer Vorlage starten",
    tpl_sub: "Jede Vorlage ist eine vollständig editierbare Remotion-Komposition.",
    tpl1_name: "Cineastisches Intro",
    tpl1_desc: "Dramatische Titeleinblendung mit Partikelspuren und Unschärfe.",
    tpl2_name: "Text-Reveal",
    tpl2_desc: "Federanimierte Zeichen mit benutzerdefiniertem Easing und Versatz.",
    tpl3_name: "Logo-Explosion",
    tpl3_desc: "Logo-Einblendung mit radialer Partikelexplosion und Glow.",
    tpl4_name: "Partikel-Sturm",
    tpl4_desc: "GPU-Partikelsimulation mit Gravitationsbrunnen und Farbverläufen.",
    tpl5_name: "Fluid-Wipe",
    tpl5_desc: "Szenenwechsel mit Fluidsimulation — organisch, weich, physikalisch.",
    tpl6_name: "Neon-Pulse",
    tpl6_desc: "Rhythmische Neon-Glow-Animation mit Partikelsynchronisation.",
    tpl_use: "Vorlage verwenden",
    tpl_preview: "Vorschau",

    price_eyebrow: "Preise",
    price_title: "Einfache, ehrliche Preise",
    price_sub: "Kostenlos starten. Upgraden wenn du mehr Exports, Auflösung oder API-Zugang brauchst.",
    price_free: "Free",
    price_free_sub: "Für immer",
    price_pro: "Pro",
    price_pro_per: "/ Monat",
    price_studio: "Studio",
    price_studio_per: "/ Monat",
    price_cta_free: "Kostenlos starten",
    price_cta_pro: "Pro-Test starten",
    price_cta_studio: "Vertrieb kontaktieren",
    price_most_popular: "Beliebteste Wahl",

    footer_tagline: "Motion-Intelligenz für jeden Creator. Powered by Remotion und GPU-Partikelphysik.",
    footer_col_product: "Produkt",
    footer_col_templates: "Vorlagen",
    footer_col_developers: "Entwickler",
    footer_col_company: "Unternehmen",
    footer_copyright: "© 2026 Mojin. Alle Rechte vorbehalten.",
    footer_made_by: "Ein Lunexo Labs Produkt.",
  },
};
